all:
  hosts:
web-srv:
  hosts:
    test1:
      ansible_ssh_host: example
      ansible_ssh_user: admin
      domain_name: test1
    test2:
      ansible_ssh_host: example
      ansible_ssh_user: admin
      domain_name: test2

